In [8]:
import numpy as np
list_no = [4,5,2]
%time np_array= np.asarray(list_no)

Wall time: 0 ns


In [10]:
%time print(np_array)

[4 5 2]
Wall time: 0 ns


In [5]:
type(np_array)

numpy.ndarray

In [6]:
print(np_array.dtype)

int32


In [7]:
print(np_array.shape)

(3,)


In [18]:
np_zeros = np.zeros((5,6),dtype=int64)

NameError: name 'int64' is not defined

In [12]:
print(np_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [17]:
print(np_zeros.dtype)

int32


In [22]:
np_linespace= np.linspace(2,5,10)

In [23]:
print(np_linespace)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


np_ones= np.ones((3,6))

In [26]:
np_ones = np.ones((5,6))

In [27]:
print(np_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [31]:
np_array =np.arange(10)
print(np_array)
np_array_shaped = np.reshape(np_array,(5,2))

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(np_array_shaped)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
print(np_array_shaped[0][1])

1


In [34]:
np_array_shaped [0,1] = 4

In [35]:
print(np_array_shaped)

[[0 4]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
np