In [1]:
import numpy as np
np_arr = np.array([[6,2],[1,6]])
print(np_arr)

[[6 2]
 [1 6]]


In [2]:
np_arr_insert = np.insert(np_arr,0,[5,6],0)
print(np_arr_insert)

[[5 6]
 [6 2]
 [1 6]]


In [3]:
np_arr_append = np.append(np_arr,[[4,5],[7,2]])

In [4]:
print(np_arr_append)

[6 2 1 6 4 5 7 2]


In [5]:
np_arr_delete = np.delete(np_arr,1,0)

In [6]:
print(np_arr_delete)

[[6 2]]


In [7]:
import numpy as np
np_arr = np.array([[6,2],[1,6]])
np_list = np_arr[np_arr >4]
print(np_list)
print(np_arr >4)

[6 6]
[[ True False]
 [False  True]]


In [11]:
np_broadcast = np_arr *2
np_3 = np.array([[2,6]])

In [9]:
print(np_broadcast)

[[12  4]
 [ 2 12]]


In [13]:
np_1 = np_arr * np_3
print(np_1)

[[12 12]
 [ 2 36]]
