In [7]:
import numpy as np
np.random.seed(4)

np_i = np.random.random(10)

print(np_i)

[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895
 0.97627445 0.00623026 0.25298236 0.43479153]


In [8]:
print(np_i)

[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895
 0.97627445 0.00623026 0.25298236 0.43479153]


In [10]:
print(np_i[1:5])

[0.54723225 0.97268436 0.71481599 0.69772882]


In [12]:
d = np.copy(np_i[1:5])

In [13]:
print(d)

[0.54723225 0.97268436 0.71481599 0.69772882]


In [14]:
d[0:1] =1

In [15]:
print(d)

[1.         0.97268436 0.71481599 0.69772882]


In [16]:
print(np_i)

[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895
 0.97627445 0.00623026 0.25298236 0.43479153]
